wso2/kubernetes-apim

artifacts/pattern-3/apim-rdbms-deployment.yaml, artifacts/pattern-3/wso2am-analytics-deployment.yaml, artifacts/pattern-3/wso2am-api-store-deployment.yaml, artifacts/pattern-3/wso2am-gateway-manager-deployment.yaml, artifacts/pattern-3/wso2am-gateway-worker-deployment.yaml
- Change docker image names to wso2 docker registry.
=> Change image names to wso2 docker registry

.gitignore, dockerfile/activemq/Dockerfile, dockerfile/api-core/Dockerfile, dockerfile/api-core/deployment.yaml, dockerfile/api-gateway/Dockerfile, dockerfile/api-gateway/gateway.sh, dockerfile/key-manager/Dockerfile, pattern-1/activemq-deployment.yaml, pattern-1/activemq-service.yaml, pattern-1/api-core-deployment.yaml, pattern-1/api-core-service.yaml, pattern-1/api-gateway-deployment.yaml, pattern-1/api-gateway-service.yaml, pattern-1/deploy-openshift.sh, pattern-1/key-manager-deployment.yaml, pattern-1/key-manager-service.yaml, pattern-1/undeploy-openshift.sh, pattern-1/undeploy.sh
This PR adds changes suggested by @pubudu538 at the initial PR to open a `3.0.0` branch, as well as some changes to ActiveMQ Dockerfile.
=> Intial changes to match M5 release numbers

dockerfile/activemq/Dockerfile, dockerfile/analytics/Dockerfile, dockerfile/api-core/Dockerfile, dockerfile/api-gateway/Dockerfile, dockerfile/api-gateway/gateway.sh, dockerfile/base/Dockerfile, dockerfile/key-manager/Dockerfile, pattern-1/api-core-deployment.yaml, pattern-1/api-core-service.yaml, pattern-1/api-gateway-deployment.yaml, pattern-1/api-gateway-service.yaml, pattern-1/deploy-openshift.sh, pattern-1/key-manager-deployment.yaml, pattern-1/key-manager-service.yaml, pattern-1/undeploy-openshift.sh
This PR includes improvements to the K8S artifacts and the Dockerfiles for M6 release.  This also includes the Dockerfile for the Analytics component.
=> M6 artifact improvements

base/analytics/Dockerfile, base/analytics/init_carbon.sh, base/apim/Dockerfile, base/apim/change_ownership.sh, base/apim/init_carbon.sh, base/apim/sudoers, base/build.sh, base/mysql/Dockerfile, base/rsync/Dockerfile, base/rsync/run.sh, base/sshd/Dockerfile, base/sshd/init.sh, pattern-1/artifacts/apim-analytics/wso2apim-analytics-service.yaml, pattern-1/artifacts/apim/wso2apim-service.yaml, pattern-1/artifacts/deploy-kubernetes.sh, pattern-1/artifacts/deploy-openshift.sh, pattern-1/artifacts/routes/wso2apim-analytics-route.yaml, pattern-1/artifacts/routes/wso2apim-gw-route.yaml, pattern-1/artifacts/routes/wso2apim-route.yaml, pattern-1/artifacts/undeploy-kubernetes.sh, pattern-1/artifacts/undeploy-openshift.sh, pattern-1/artifacts/volumes/persistent-volumes.yaml, pattern-1/confs/apim-analytics-1/repository/conf/tomcat/catalina-server.xml, pattern-1/confs/apim-analytics-2/repository/conf/tomcat/catalina-server.xml, pattern-1/confs/apim-manager-worker/repository/conf/api-manager.xml, pattern-1/confs/apim-manager-worker/repository/conf/tomcat/catalina-server.xml, pattern-1/confs/apim-worker/repository/conf/api-manager.xml, pattern-1/confs/apim-worker/repository/conf/tomcat/catalina-server.xml
PR adds routes to expose services. Also included missing license headers.
=> Adding routes to expose services

base/analytics/Dockerfile, base/analytics/change_ownership.sh, base/analytics/init_carbon.sh, base/analytics/sudoers, pattern-1/artifacts/apim-analytics/wso2apim-analytics-1-deployment.yaml, pattern-1/artifacts/apim-analytics/wso2apim-analytics-1-service.yaml, pattern-1/artifacts/apim-analytics/wso2apim-analytics-2-deployment.yaml, pattern-1/artifacts/apim-analytics/wso2apim-analytics-2-service.yaml, pattern-1/artifacts/apim-analytics/wso2apim-analytics-volume-claim.yaml, pattern-1/artifacts/deploy-kubernetes.sh, pattern-1/artifacts/undeploy-kubernetes.sh, pattern-1/artifacts/volumes/persistent-volumes.yaml
> Updating APIM-analytics configs for kubernetes deployment
> Hard-code unique my-node-id for each analytics node
> Add a configmap to mount <APIM_ANALYTICS_HOME>/repository/conf/analytics/my-node-id.dat to file system.
> Add a volume mount to mount  <APIM_ANALYTICS_HOME>/repository/data to the file system
> Expose ports needed for cluster communication as specified in [DAS Specific Ports](https://docs.wso2.com/display/DAS300/WSO2+DAS+Specific+Ports)
> Update init_carbon.sh to expose pod IP as SPARK_LOCAL_IP environmental variable.
> Adding volumes for analytics nodes in persistent-volumes file.
> Adding hazelcast.properties file.
> N/A
> N/A
> N/A
> N/A
> N/A
> N/A
- Unit tests 
> N/A
- Integration tests
> N/A
- Followed secure coding standards in …
=> APIM analyics config updates for kubernetes deployment

pattern-2/artifacts/apim-is-as-km/wso2apim-is-km-volume-claim.yaml
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Removing pattern-2.1 label

pattern-1/confs/apim-analytics-1/repository/conf/analytics/analytics-config.xml, pattern-1/confs/apim-analytics-1/repository/conf/datasources/analytics-datasources.xml, pattern-1/confs/apim-analytics-2/repository/conf/analytics/analytics-config.xml, pattern-1/confs/apim-analytics-2/repository/conf/datasources/analytics-datasources.xml
> Add data purging and resolve database conflicts.
> Add analytics-config.xml file and change the databases names in analytics-datasources.xml file.
=> Add data purging and corrected the database names

pattern-1/artifacts/apim-analytics/wso2apim-analytics-1-deployment.yaml, pattern-1/artifacts/apim-analytics/wso2apim-analytics-1-service.yaml, pattern-1/artifacts/apim-analytics/wso2apim-analytics-2-deployment.yaml, pattern-1/artifacts/apim-analytics/wso2apim-analytics-2-service.yaml
> Resolve the port conflict issue.
> Assign different port numbers.
=> Resolved the port conflicts

automation-scripts/README.txt, automation-scripts/common/scripts/base.sh, automation-scripts/common/scripts/wait-until-server-starts.sh, automation-scripts/deploy.sh, automation-scripts/privileged_deploy.sh
> This PR contains the automation scripts of APIM 2.1.0 pattern deployment in K8s.
> The goal is to automate the pattern deployment in K8s.
> Wrote scripts to automate the pattern deployment.
> No
> Automation scripts of APIM 2.1.0 pattern deployment in K8s
> No
> N/A
> N/A
> N/A
N/A
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
- Ran FindSecurityBugs plugin and verified report? yes
- Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes
> No
> No
> No
> N/A
>
=> Add automation scripts of APIM 2.1.0 pattern deployment in K8s

README.md, helm/pattern-1/README.md, helm/pattern-2/README.md, pattern-1/README.md, pattern-1/scripts/README.md, pattern-2/README.md, pattern-2/scripts/README.md
> Update README.md documentation of Kubernetes and Helm resources. This fixes https://github.com/wso2/kubernetes-apim/issues/114.
> Update README.md documentation of Kubernetes and Helm resources.
=> Update README.md documentation of Kubernetes and Helm resources

helm/pattern-2/README.md
> Fix folder path in README.md documentation
> Fix folder path in README.md documentation.
=> Fix folder path in README.md documentation

CHANGELOG.md, ManageConfigurations.md, README.md, pattern-1/apim-analytics/wso2apim-analytics-deployment.yaml, pattern-1/apim/wso2apim-deployment.yaml, pattern-1/confs/apim-analytics/registry.xml, pattern-1/confs/apim/registry.xml, pattern-1/scripts/undeploy.sh, pattern-2/apim-analytics/wso2apim-analytics-deployment.yaml, pattern-2/apim-gw/wso2apim-gateway-deployment.yaml, pattern-2/apim-is-as-km/wso2apim-is-as-km-deployment.yaml, pattern-2/apim-km/wso2apim-km-deployment.yaml, pattern-2/apim-pubstore-tm/wso2apim-pubstore-tm-1-deployment.yaml, pattern-2/apim-pubstore-tm/wso2apim-pubstore-tm-2-deployment.yaml, pattern-2/confs/apim-analytics/registry.xml, pattern-2/confs/apim-gateway/registry.xml, pattern-2/confs/apim-is-as-km/registry.xml, pattern-2/confs/apim-km/registry.xml, pattern-2/confs/apim-pubstore-tm-1/registry.xml, pattern-2/confs/apim-pubstore-tm-2/registry.xml, pattern-2/scripts/deploy.sh
> This refines documentation based on recent changes to Docker resources. Further defines resource requirements for product deployments. This fixes https://github.com/wso2/kubernetes-apim/issues/136.
> Refines documentation based on recent changes to Docker resources. Further defines resource requirements for product deployments.
=> Refinements to Kubernetes artifacts for WSO2 API Manager v2.2.x

helm/pattern-1/apim-with-analytics/templates/wso2apim-deployment.yaml
>  Merge all the changes in the 2.6.x branch into the Master branch
Fixes #169
=> Merger 2.6.x branch into Master branch

pattern-1/README.md, pattern-1/apim-analytics/wso2apim-analytics-deployment.yaml, pattern-1/apim/wso2apim-deployment.yaml, pattern-1/scripts/README.md, pattern-1/scripts/deploy.sh, pattern-1/scripts/undeploy.sh
> Improves Kubernetes resources for WSO2 API Management pattern 1 by upgrading the Kubernetes API version for Deployment resources and setting resource requests and limits. Further, integrates support in Kubernetes resources for users with and without WSO2 subscriptions. This fixes https://github.com/wso2/kubernetes-apim/issues/73, fixes https://github.com/wso2/kubernetes-apim/issues/148, fixes https://github.com/wso2/kubernetes-apim/issues/178 and fixes https://github.com/wso2/kubernetes-apim/issues/180.
> Improves Kubernetes resources for WSO2 API Management pattern 1 and integrates support in Kubernetes resources for users with and without WSO2 subscriptions.
=> Review Kubernetes resources for deployment pattern 1

CHANGELOG.md, README.md, pattern-2/README.md
> Introduce a change log and fix documentation issues.
> Introduce a change log and fix documentation issues
=> Add Change Log

CHANGELOG.md, README.md, advanced/pattern-2/scripts/deploy.sh
> Uncomment erroneously commented out Kubernetes client commands.
> Uncomment erroneously commented out Kubernetes client commands
=> Uncomment erroneously commented out Kubernetes client commands

CHANGELOG.md, README.md
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Adding v2.6.0.6 to changelog

CHANGELOG.md, README.md
Merge 2.6.x-changelog branch into Master branch
=> Merge 2.6.x-changelog branch into Master branch

README.md
> Fix README change log link prior to v2.6.0.6 release.
> Fix README change log link
=> Fix README change log link

README.md
> Merge 2.6.x branch to master branch - 20/06/2019.
=> Merge 2.6.x branch to master branch

CHANGELOG.md
> Update change log with appropriate release year.
> Update change log with appropriate release year
=> Update change log with appropriate release year

CHANGELOG.md
Merge 2.6.x Branch into Master branch
=> Merge 2.6.x-rebase Branch into Master branch

advanced/pattern-1/README.md
Update readme on not supporting scale-up in pattern 1
=> Update readme on not supporting scale-up in pattern 1

CHANGELOG.md, README.md, advanced/pattern-2/README.md, advanced/pattern-3/README.md, advanced/pattern-3/apim-analytics/wso2apim-analytics-deployment.yaml, advanced/pattern-3/apim-gateway/wso2apim-gateway-deployment.yaml, advanced/pattern-3/apim-is-as-km/wso2apim-is-as-km-deployment.yaml, advanced/pattern-3/apim-km/wso2apim-km-deployment.yaml, advanced/pattern-3/apim-publisher/wso2apim-publisher-deployment.yaml, advanced/pattern-3/apim-store/wso2apim-store-deployment.yaml, advanced/pattern-3/apim-tm/wso2apim-tm-1-deployment.yaml, advanced/pattern-3/apim-tm/wso2apim-tm-2-deployment.yaml, advanced/pattern-3/extras/rdbms/volumes/persistent-volumes.yaml, advanced/pattern-3/scripts/deploy.sh, advanced/pattern-3/scripts/undeploy.sh, advanced/pattern-3/volumes/persistent-volumes.yaml
> This PR introduces Kubernetes Init Containers in Kubernetes resources for WSO2 API Management deployment pattern 3. This fixes https://github.com/wso2/kubernetes-apim/issues/224 and fixes https://github.com/wso2/kubernetes-apim/issues/236.
> Introduce Kubernetes Init Containers in Kubernetes resources for WSO2 API Management deployment pattern 3
=> Introduce Kubernetes Init Containers in Kubernetes resources for WSO2 API Management deployment pattern 3

advanced/helm/pattern-2/apim-gw-km-with-analytics/templates/wso2apim-gateway-volume-claim.yaml, advanced/helm/pattern-2/apim-gw-km-with-analytics/templates/wso2apim-is-as-km-volume-claim.yaml, advanced/helm/pattern-2/apim-gw-km-with-analytics/templates/wso2apim-pub-store-tm-volume-claim.yaml
- Change ".Values.cloudProvider" to ".Values.wso2.deployment.persistentRuntimeArtifacts.cloudProvider"
- ignore matchLabel selector for azurefile pvc
=> Fix incorrect template variable and remove purpose label for azurefiles

simple/README.md
> Broken link to the illustration in simple/README.md
> Fix the broken link in [1]
[1] [README.md] - simplified setup (https://github.com/NishikaDeSilva/kubernetes-apim/blob/2.6.x/simple/README.md)
=> Fix broken link in simple/README.md

CHANGELOG.md
- Update changelog for release 3.0.0.1
=> Update changelog for release 3.0.0.1

advanced/pattern-3/apim-gateway/wso2apim-gateway-deployment.yaml, advanced/pattern-3/apim-gateway/wso2apim-gateway-volume-claim.yaml, advanced/pattern-3/apim-tm/wso2apim-tm-1-deployment.yaml, advanced/pattern-3/apim-tm/wso2apim-tm-2-deployment.yaml, advanced/pattern-3/apim-tm/wso2apim-tm-volume-claim.yaml, advanced/pattern-3/volumes/persistent-volumes.yaml
> This PR adds persistent volumes to synapse-configs directory in APIM-Gateway nodes and executionplans directory in APIM-Traffic manager nodes. Fixes #276
=> Add persistent volume to pattern-3

advanced/pattern-2/README.md, advanced/pattern-2/scripts/README.md, advanced/pattern-3/README.md, advanced/pattern-3/scripts/README.md
> Update the README files to suit with the latest artifact synchronisation. Fixes #273.
=> Update README files

advanced/am-pattern-1/README.md
Update Readme for APIM 3.0.0 pattern-1 Helm resources
=> Fix Readme for pattern-1 of APIM 3.0.0

CHANGELOG.md, README.md, advanced/am-pattern-1/Chart.yaml
Update changelog and chart version for release 3.0.0.2
=> Update changelog and chart version for release 3.0.0.2

CHANGELOG.md
Update release date and milestone for release 3.0.0.2
=> Update release date and milestone for release 3.0.0.2

advanced/am-pattern-1/requirements.yaml, advanced/mysql-am/Chart.yaml
=> Update mysql-am chart version

advanced/am-pattern-1/README.md
Remove NGINX version requirement from README.md
=> Remove NGINX version requirement from README.md

advanced/am-pattern-1/README.md
Fix incorrect link to kubernetes setup documentation
=> Fix incorrect link to kubernetes setup documentation

CHANGELOG.md, README.md, advanced/helm/am-pattern-1/Chart.yaml, advanced/helm/am-pattern-1/requirements.yaml, advanced/helm/am-pattern-1/values.yaml, advanced/helm/am-pattern-2/Chart.yaml, advanced/helm/am-pattern-2/requirements.yaml, advanced/helm/am-pattern-2/templates/wso2am-pattern-2-secrets.yaml, advanced/helm/am-pattern-2/values.yaml, advanced/helm/mysql-am/Chart.yaml, advanced/pattern-1/README.md, advanced/pattern-2/README.md, advanced/pattern-3/README.md
This PR addresses the following issues.
- Fixes incorrect secret definition that causes deployment to fail when using subscription. #305 
- Reduce minReadySeconds to 30 from 240 to avoid long delays. #304 
- Upgrade incorrect chart version for am-pattern-1
=> Fix incorrect secret issue

advanced/am-pattern-1/Chart.yaml, advanced/am-pattern-1/requirements.yaml, advanced/mysql-am/Chart.yaml
Update chart version for 3.0.0.3
=> Update chart version for 3.0.0.3

CHANGELOG.md, README.md
> Update CHANGELOG for release v3.0.0.3
=> Update CHANGELOG for release v3.0.0.3

advanced/pattern-3/apim-gateway/wso2apim-gateway-deployment.yaml, advanced/pattern-3/apim-tm/wso2apim-tm-2-deployment.yaml
> Fixing issue[1]
[1]. https://github.com/wso2/kubernetes-apim/issues/323
> Link to the PR for changes to the training content in …
=> fixing ssl handshake issue.

advanced/am-pattern-1/confs/am/instance-1/repository/conf/deployment.toml, advanced/am-pattern-1/confs/am/instance-2/repository/conf/deployment.toml
This PR modifies throttling configurations in deployment.toml
Since throttling was not working with earlier configurations modified them
=> Modify throttling configurations in deployment.toml

advanced/am-pattern-1/README.md
Mention supported versions of Kubernetes and Helm
=> Mention supported versions of Kubernetes and Helm

advanced/am-pattern-1/templates/am-analytics/dashboard/wso2am-pattern-1-am-analytics-dashboard-deployment.yaml, advanced/am-pattern-1/templates/am/instance-2/wso2am-pattern-1-am-2-deployment.yaml
Removing unnecessary init containers
> Link to the PR for changes to the training content in …
=> Removing unnecessary init containers

CHANGELOG.md, simple/deployment-scripts/wso2am-ga.sh, simple/deployment-scripts/wso2am-latest.sh
> Add GA script and fixes #349
=> Fix docker registry hostname and add GA script

advanced/am-pattern-1/README.md, advanced/am-pattern-2/README.md
Rename incorrect reference `apim-pattern-1` to `am-pattern-1`
=> Rename apim-pattern-1 to am-pattern-1

advanced/helm/am-pattern-2/confs/am-pub-store-tm-1/api-manager.xml, advanced/helm/am-pattern-2/confs/am-pub-store-tm-2/api-manager.xml, advanced/pattern-2/confs/apim-pub-store-tm-1/api-manager.xml, advanced/pattern-2/confs/apim-pub-store-tm-2/api-manager.xml, advanced/pattern-3/confs/apim-publisher/api-manager.xml
Resolves https://github.com/wso2/kubernetes-apim/issues/318
> Link to the PR for changes to the training content in …
=> Point AuthManager of store/pub to localhost

simple/deployment-scripts/wso2am-ga.sh, simple/deployment-scripts/wso2am-latest.sh
- Fix the issue in the `if` condition of the deployment shell script.
=> Fix if condition in deployment shell script

advanced/pattern-3/apim-tm/wso2apim-tm-1-deployment.yaml, advanced/pattern-3/apim-tm/wso2apim-tm-2-deployment.yaml, advanced/pattern-3/routes/wso2apim-gateway-route.yaml, advanced/pattern-3/routes/wso2apim-km-route.yaml, advanced/pattern-3/routes/wso2apim-publisher-route.yaml, advanced/pattern-3/routes/wso2apim-store-route.yaml, advanced/pattern-3/scripts/oc-deploy.sh
Traffic Manager nodes will not start and will throw an error as there is no docker-entrypoint.sh in the 2.6.0 latest image.
> …
=> artifacts and changes in pattern-3 openshift deployment

simple/deployment-scripts/wso2am-ga.sh, simple/deployment-scripts/wso2am-latest.sh, simple/funcs, simple/funcs4opensource
> Correct minikube check condition
> Check if the cluster is minikube, before extracting the cluster ip.
=> Correct minikube check condition

advanced/am-pattern-1/README.md, advanced/am-pattern-2/README.md, advanced/am-pattern-3/README.md
> This PR reviews documentation of WSO2 API Management Pattern Helm resources. This fixes https://github.com/wso2/kubernetes-apim/issues/372 and fixes https://github.com/wso2/kubernetes-apim/issues/392.
> Review Documentation of WSO2 API Management Pattern Helm Resources
=> [v3.1.x] Review Documentation of WSO2 API Management Pattern Helm Resources

CHANGELOG.md, README.md, simple/README.md
> This PR updates the change log documentation for release `v3.1.0.3`.
> Update change log documentation for a new release - 2020-07-20
=> [v3.1.x] Update change log documentation for release v3.1.0.3

advanced/am-pattern-1/README.md, advanced/am-pattern-2/README.md, advanced/am-pattern-3/README.md
> This PR updates the deployment diagrams of the README documentation.
> Update README documentation deployment diagrams
=> [v3.1.x] Update README Documentation Deployment Diagrams

advanced/am-pattern-1/README.md, advanced/am-pattern-2/README.md, advanced/am-pattern-3/README.md
> This PR merges `3.1.x` branch to the `master` branch.
> Merge 3.1.x branch to the master branch
=> Merge 3.1.x branch to the master branch - 2020-07-20

advanced/am-pattern-1/README.md, advanced/am-pattern-2/README.md, advanced/am-pattern-3/README.md
> This PR performs $subject adding documentation with regards to the following.
>   - Tested storage options
>   - Managing keystores and truststores
> Add documentation for advanced usage scenarios
=> [3.2.0] Add Documentation For Advanced Usage Scenarios

advanced/am-pattern-1/templates/am-analytics/dashboard/wso2am-pattern-1-am-analytics-dashboard-bin.yaml, advanced/am-pattern-1/templates/am-analytics/dashboard/wso2am-pattern-1-am-analytics-dashboard-deployment.yaml, advanced/am-pattern-1/templates/am-analytics/worker/wso2am-pattern-1-am-analytics-worker-bin.yaml, advanced/am-pattern-1/templates/am-analytics/worker/wso2am-pattern-1-am-analytics-worker-statefulset.yaml, advanced/am-pattern-1/templates/am/instance-1/wso2am-pattern-1-am-deployment.yaml, advanced/am-pattern-1/templates/am/instance-2/wso2am-pattern-1-am-deployment.yaml, advanced/am-pattern-1/values.yaml, advanced/am-pattern-2/templates/am-analytics/dashboard/wso2am-pattern-2-am-analytics-dashboard-bin.yaml, advanced/am-pattern-2/templates/am-analytics/dashboard/wso2am-pattern-2-am-analytics-dashboard-deployment.yaml, advanced/am-pattern-2/templates/am-analytics/worker/wso2am-pattern-2-am-analytics-worker-bin.yaml, advanced/am-pattern-2/templates/am-analytics/worker/wso2am-pattern-2-am-analytics-worker-statefulset.yaml, advanced/am-pattern-2/templates/am/gateway/wso2am-pattern-2-am-gateway-deployment.yaml, advanced/am-pattern-2/templates/am/km/wso2am-pattern-2-am-km-statefulset.yaml, advanced/am-pattern-2/templates/am/pub-devportal-tm/instance-1/wso2am-pattern-2-am-deployment.yaml, advanced/am-pattern-2/templates/am/pub-devportal-tm/instance-2/wso2am-pattern-2-am-deployment.yaml, advanced/am-pattern-2/values.yaml, advanced/am-pattern-3/templates/am-analytics/dashboard/wso2am-pattern-3-am-analytics-dashboard-bin.yaml, advanced/am-pattern-3/templates/am-analytics/dashboard/wso2am-pattern-3-am-analytics-dashboard-deployment.yaml, advanced/am-pattern-3/templates/am-analytics/worker/wso2am-pattern-3-am-analytics-worker-bin.yaml, advanced/am-pattern-3/templates/am-analytics/worker/wso2am-pattern-3-am-analytics-worker-statefulset.yaml, advanced/am-pattern-3/templates/am/devportal/instance-1/wso2am-pattern-3-am-devportal-deployment.yaml, advanced/am-pattern-3/templates/am/devportal/instance-2/wso2am-pattern-3-am-devportal-deployment.yaml, advanced/am-pattern-3/templates/am/gateway/wso2am-pattern-3-am-gateway-deployment.yaml, advanced/am-pattern-3/templates/am/km/wso2am-pattern-3-am-km-statefulset.yaml, advanced/am-pattern-3/templates/am/publisher/instance-1/wso2am-pattern-3-am-publisher-deployment.yaml, advanced/am-pattern-3/templates/am/publisher/instance-2/wso2am-pattern-3-am-publisher-deployment.yaml, advanced/am-pattern-3/templates/am/tm/wso2am-pattern-3-am-tm-statefulset.yaml, advanced/am-pattern-3/values.yaml
> This PR performs $subject thus fixing the linked issue.
> Allocate memory for JVM heap
> Helm version: `3.2.4`
> GKE based Kubernetes Server version: `1.15`+, Git Version: `v1.15.12-gke.2`
> Product Docker images from DockerHub's WSO2 organization
=> [3.2.0] Allocate Memory for JVM Heap

CHANGELOG.md, CONTRIBUTING.md, README.md
> This PR performs $subject.
> Update change log documentation for release `v3.2.0.1`
=> [3.2.0] Update CHANGELOG Documentation for Release v3.2.0.1

simple/README.md, simple/deployment-scripts/wso2am-ga.sh, simple/deployment-scripts/wso2am-latest.sh, simple/funcs, simple/funcs4opensource, simple/kubernetes-apim-analytics/dashboard/wso2am-pattern-1-analytics-dashboard-conf.yaml, simple/kubernetes-apim-analytics/dashboard/wso2am-pattern-1-analytics-dashboard-deployment.yaml, simple/kubernetes-apim-analytics/worker/wso2apim-analytics-worker-deployment.yaml, simple/kubernetes-apim/wso2apim-conf.yaml, simple/kubernetes-apim/wso2apim-deployment.yaml, simple/kubernetes-apim/wso2apim-service.yaml
> Update Kubernetes simplified resources
> Reduce resource limits for the simplified setup
- apim 1GB
- analytics 1GB 
Resolves #459 
> Make the script compatible for docker desktop; Kubernetes 
Resolves #460
> Remove port offset
> Parameterize the waiting time before terminating the script.
> minikube 
> docker for desktop
=> Update Kubernetes simplified resources

advanced/am-pattern-1/Chart.yaml, advanced/am-pattern-2/Chart.yaml, advanced/am-pattern-3/Chart.yaml, advanced/mysql-am/Chart.yaml
> Update Helm Chart Version
> New release with simplified setup changes
=> Update Helm Chart Version

CHANGELOG.md, README.md
> Update change log documentation for release v3.2.0.2
=> Update change log documentation for release v3.2.0.2

CHANGELOG.md
> Update release Date in CHANGELOG.
=> Update release Date

CHANGELOG.md, README.md, advanced/am-pattern-1/Chart.yaml, advanced/am-pattern-2/Chart.yaml, advanced/am-pattern-3/Chart.yaml, advanced/mysql-am/Chart.yaml, simple/README.md, simple/deployment-scripts/wso2am-ga.sh, simple/deployment-scripts/wso2am-latest.sh, simple/funcs, simple/funcs4opensource, simple/kubernetes-apim-analytics/dashboard/wso2am-pattern-1-analytics-dashboard-conf.yaml, simple/kubernetes-apim-analytics/dashboard/wso2am-pattern-1-analytics-dashboard-deployment.yaml, simple/kubernetes-apim-analytics/worker/wso2apim-analytics-worker-deployment.yaml, simple/kubernetes-apim/wso2apim-conf.yaml, simple/kubernetes-apim/wso2apim-deployment.yaml, simple/kubernetes-apim/wso2apim-service.yaml
> This PR merges the 3.2.x branch to the master branch.
> Merge 3.2.x branch to the master branch
=> Merge 3.2.x branch to the master branch - 2020-09-16 

CHANGELOG.md, README.md, advanced/am-pattern-1/Chart.yaml, advanced/am-pattern-1/README.md, advanced/am-pattern-1/requirements.yaml, advanced/am-pattern-2/Chart.yaml, advanced/am-pattern-2/README.md, advanced/am-pattern-2/requirements.yaml, advanced/am-pattern-3/Chart.yaml, advanced/am-pattern-3/README.md, advanced/am-pattern-3/requirements.yaml, advanced/mysql-am/Chart.yaml
> This PR prepares the repository for the release `v3.1.0.4`. This PR fixes #471.
=> [3.1.0] Preparing for the release v3.1.0.4

advanced/am-pattern-1/templates/_helpers.tpl, advanced/am-pattern-1/templates/am-analytics/dashboard/wso2am-pattern-1-am-analytics-dashboard-deployment.yaml, advanced/am-pattern-1/templates/am-analytics/worker/wso2am-pattern-1-am-analytics-worker-statefulset.yaml, advanced/am-pattern-1/templates/am/instance-1/wso2am-pattern-1-am-deployment.yaml, advanced/am-pattern-1/templates/am/instance-2/wso2am-pattern-1-am-deployment.yaml, advanced/am-pattern-2/templates/_helpers.tpl, advanced/am-pattern-2/templates/am-analytics/dashboard/wso2am-pattern-2-am-analytics-dashboard-deployment.yaml, advanced/am-pattern-2/templates/am-analytics/worker/wso2am-pattern-2-am-analytics-worker-statefulset.yaml, advanced/am-pattern-2/templates/am/gateway/wso2am-pattern-2-am-gateway-deployment.yaml, advanced/am-pattern-2/templates/am/km/wso2am-pattern-2-am-km-statefulset.yaml, advanced/am-pattern-2/templates/am/pub-devportal-tm/instance-1/wso2am-pattern-2-am-deployment.yaml, advanced/am-pattern-2/templates/am/pub-devportal-tm/instance-2/wso2am-pattern-2-am-deployment.yaml, advanced/am-pattern-3/templates/_helpers.tpl, advanced/am-pattern-3/templates/am-analytics/dashboard/wso2am-pattern-3-am-analytics-dashboard-deployment.yaml, advanced/am-pattern-3/templates/am-analytics/worker/wso2am-pattern-3-am-analytics-worker-statefulset.yaml, advanced/am-pattern-3/templates/am/devportal/instance-1/wso2am-pattern-3-am-devportal-deployment.yaml, advanced/am-pattern-3/templates/am/devportal/instance-2/wso2am-pattern-3-am-devportal-deployment.yaml, advanced/am-pattern-3/templates/am/gateway/wso2am-pattern-3-am-gateway-deployment.yaml, advanced/am-pattern-3/templates/am/km/wso2am-pattern-3-am-km-statefulset.yaml, advanced/am-pattern-3/templates/am/publisher/instance-1/wso2am-pattern-3-am-publisher-deployment.yaml, advanced/am-pattern-3/templates/am/publisher/instance-2/wso2am-pattern-3-am-publisher-deployment.yaml, advanced/am-pattern-3/templates/am/tm/wso2am-pattern-3-am-tm-statefulset.yaml, advanced/mysql-am/requirements.yaml
Use Updates 2.0 images when subscription is enabled.
Resolves #478, Resolves #479
=> Use Updates 2.0 images when subscription is enabled

.gitignore, advanced/am-pattern-1/requirements.yaml, advanced/am-pattern-2/requirements.yaml, advanced/am-pattern-3/requirements.yaml
Use nfs-server-provisioner from kvaps since stable chart is deprecated
=> Use nfs-server-provisioner from kvaps

CHANGELOG.md, advanced/am-pattern-1/Chart.yaml, advanced/am-pattern-1/requirements.yaml, advanced/am-pattern-2/Chart.yaml, advanced/am-pattern-2/requirements.yaml, advanced/am-pattern-3/Chart.yaml, advanced/am-pattern-3/requirements.yaml, advanced/mysql-am/Chart.yaml
=> Prepare for relase 3.2.0.3

advanced/am-pattern-1/requirements.yaml, advanced/am-pattern-2/requirements.yaml, advanced/am-pattern-3/requirements.yaml, advanced/mysql-am/requirements.yaml
Use MySQL, nfs-server-provisioner from WSO2 repo
=> Use MySQL, nfs-server-provisioner from WSO2 repo

CHANGELOG.md, advanced/am-pattern-1/Chart.yaml, advanced/am-pattern-1/requirements.yaml, advanced/am-pattern-2/Chart.yaml, advanced/am-pattern-2/requirements.yaml, advanced/am-pattern-3/Chart.yaml, advanced/am-pattern-3/requirements.yaml, advanced/mysql-am/Chart.yaml
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Prepare for 3.2.0.4 Release

CHANGELOG.md, advanced/am-pattern-1/Chart.yaml, advanced/am-pattern-1/requirements.yaml, advanced/am-pattern-2/Chart.yaml, advanced/am-pattern-2/requirements.yaml, advanced/am-pattern-3/Chart.yaml, advanced/am-pattern-3/requirements.yaml, advanced/mysql-am/Chart.yaml, advanced/mysql-am/requirements.yaml
$subject
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type …
=> Prepare for Release 3.2.0.4

advanced/am-pattern-1/README.md, advanced/am-pattern-2/README.md, advanced/am-pattern-3/README.md
=> Update patterns README.md files

advanced/am-pattern-1/README.md, advanced/am-pattern-1/templates/am/instance-1/wso2am-pattern-1-am-conf.yaml, advanced/am-pattern-1/templates/am/instance-2/wso2am-pattern-1-am-conf.yaml, advanced/am-pattern-1/values.yaml, advanced/am-pattern-2/README.md, advanced/am-pattern-2/values.yaml, advanced/am-pattern-3/README.md, advanced/am-pattern-3/templates/am/gateway/wso2am-pattern-3-am-gateway-conf.yaml, advanced/am-pattern-3/values.yaml, simple/am-single/README.md, simple/am-single/templates/NOTES.txt, simple/am-single/templates/am/instance/wso2am-single-node-am-conf.yaml, simple/am-single/values.yaml
This PR adds Choreo Analytics support for am-single-node, patter-1, pattern-2, and pattern-3.
Fixes https://github.com/wso2/kubernetes-apim/issues/500
=> Add Analytics configs for Helm charts

advanced/am-pattern-1/templates/NOTES.txt, advanced/am-pattern-1/templates/mi/instance-1/wso2am-pattern-1-mi-deployment.yaml, advanced/am-pattern-2/templates/NOTES.txt, advanced/am-pattern-2/templates/mi/instance-2/wso2am-pattern-2-mi-deployment.yaml, advanced/am-pattern-3/templates/am/gateway/wso2am-pattern-3-am-gateway-conf.yaml
Minor improvements to helm charts.
=> Add initContainers and update docs

advanced/am-pattern-2/templates/_helpers.tpl
=> Override pattern-1 prefix in pattern-2

advanced/am-pattern-1/templates/_helpers.tpl, advanced/am-pattern-1/templates/mi/instance-1/wso2am-pattern-1-mi-deployment.yaml, advanced/am-pattern-1/templates/wso2am-pattern-1-mi-secrets.yaml, advanced/am-pattern-2/README.md, advanced/am-pattern-2/templates/_helpers.tpl, advanced/am-pattern-2/templates/mi/instance-2/wso2am-pattern-2-mi-deployment.yaml, advanced/am-pattern-2/templates/wso2am-pattern-2-secrets.yaml, advanced/am-pattern-2/values.yaml, advanced/am-pattern-3/templates/_helpers.tpl, advanced/am-pattern-3/templates/mi/instance-1/wso2am-pattern-3-mi-deployment.yaml, advanced/am-pattern-3/templates/wso2am-pattern-3-mi-secrets.yaml
=> Issue while deploying private docker images for mi deployment

advanced/am-pattern-1/templates/am/instance-1/wso2am-pattern-1-am-conf.yaml, advanced/am-pattern-1/templates/am/instance-2/wso2am-pattern-1-am-conf.yaml
=> Adding allowall config to am passthrugh sender

advanced/am-pattern-2/README.md
=> Update pattern-2 readme

advanced/am-pattern-1/README.md, advanced/am-pattern-2/README.md, advanced/am-pattern-2/values.yaml, advanced/am-pattern-3/README.md
=> Change analytics confs and docs

advanced/am-pattern-1/README.md, advanced/am-pattern-2/README.md, advanced/am-pattern-3/README.md
$subject
Related issue: https://github.com/wso2/kubernetes-apim/issues/517
=> [4.0.x] Add steps to deploy APIM without MI

advanced/am-pattern-1/README.md, advanced/am-pattern-2/README.md, advanced/am-pattern-3/README.md
$subject
Related issue: https://github.com/wso2/kubernetes-apim/issues/517
=> Add steps to deploy APIM without MI

advanced/am-pattern-3/templates/am/control-plane/wso2am-pattern-3-am-control-plane-ingress.yaml, advanced/am-pattern-3/templates/am/gateway/wso2am-pattern-3-am-gateway-ingress.yaml, advanced/am-pattern-3/templates/am/gateway/wso2am-pattern-3-am-websub-ingress.yaml, advanced/am-pattern-3/templates/mi/instance-1/wso2am-pattern-3-mi-management-ingress.yaml, advanced/am-pattern-3/values.yaml
> Performs $subject for API Manager pattern 3 deployment. This addresses https://github.com/wso2/kubernetes-apim/issues/522.
> Performs $subject for API Manager pattern 3 deployment.
> Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3"}
> Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1"}
=> [Pattern-3] Upgrade the API version of Kubernetes Ingress resources

advanced/am-pattern-3/templates/am/control-plane/instance-1/wso2am-pattern-3-am-control-plane-deployment.yaml, advanced/am-pattern-3/templates/am/control-plane/instance-2/wso2am-pattern-3-am-control-plane-deployment.yaml, advanced/am-pattern-3/templates/am/gateway/wso2am-pattern-3-am-gateway-deployment.yaml, advanced/am-pattern-3/templates/mi/instance-1/wso2am-pattern-3-mi-deployment.yaml, advanced/am-pattern-3/values.yaml
> Performs $subject for API Manager pattern 3 deployment. This addresses https://github.com/wso2/kubernetes-apim/issues/396.
> Performs $subject for API Manager pattern 3 deployment.
> Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3"}
> Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1"}
=> [Pattern-3] Integrate Startup Probes for Product Profile Deployments

.gitignore, advanced/am-pattern-4/templates/NOTES.txt, advanced/mysql-am/Chart.yaml
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …
=> Added Note.txt file with changes

README.md
> To add guidelines about how to resolve the JWKS endpoint issue.
> To add guideline about how to add support for multiple domain names.
=> Update repository Readme for 4.1.0 release

advanced/am-pattern-3/requirements.yaml, advanced/am-pattern-3/templates/am/control-plane/instance-1/wso2am-pattern-3-am-control-plane-conf.yaml, advanced/am-pattern-3/templates/am/control-plane/instance-1/wso2am-pattern-3-am-control-plane-deployment.yaml, advanced/am-pattern-3/templates/am/control-plane/instance-2/wso2am-pattern-3-am-control-plane-conf.yaml, advanced/am-pattern-3/templates/am/control-plane/instance-2/wso2am-pattern-3-am-control-plane-deployment.yaml, advanced/am-pattern-3/templates/am/gateway/wso2am-pattern-3-am-gateway-deployment.yaml, advanced/am-pattern-3/templates/mi/instance-1/wso2am-pattern-3-mi-deployment.yaml, advanced/am-pattern-3/values.yaml, advanced/am-pattern-4/requirements.yaml, advanced/am-pattern-4/templates/am/control-plane/instance-1/wso2am-pattern-4-am-control-plane-conf.yaml, advanced/am-pattern-4/templates/am/control-plane/instance-1/wso2am-pattern-4-am-control-plane-deployment.yaml, advanced/am-pattern-4/templates/am/control-plane/instance-2/wso2am-pattern-4-am-control-plane-conf.yaml, advanced/am-pattern-4/templates/am/control-plane/instance-2/wso2am-pattern-4-am-control-plane-deployment.yaml, advanced/am-pattern-4/templates/am/gateway/wso2am-pattern-4-am-gateway-deployment.yaml, advanced/am-pattern-4/templates/am/traffic-manager/instance-1/wso2am-pattern-4-am-trafficmanager-deployment.yaml, advanced/am-pattern-4/templates/am/traffic-manager/instance-2/wso2am-pattern-4-am-trafficmanager-deployment.yaml, advanced/am-pattern-4/templates/mi/wso2am-pattern-4-mi-deployment.yaml, advanced/am-pattern-4/values.yaml
> Parameterize database configuration values  in helm chart
> Deployment.toml conf file contents updated with value.yaml file paramters. 
> Test grid Kubernetes deployment pipeline.
=> Parameterized DB config values in pattern 3 and 4

README.md
> Fix https://github.com/wso2/kubernetes-apim/pull/538#discussion_r922235317
=> Fix Readme doc issues

advanced/am-pattern-3/requirements.yaml, advanced/am-pattern-3/templates/am/control-plane/instance-1/wso2am-pattern-3-am-control-plane-conf.yaml, advanced/am-pattern-3/templates/am/control-plane/instance-1/wso2am-pattern-3-am-control-plane-deployment.yaml, advanced/am-pattern-3/templates/am/control-plane/instance-2/wso2am-pattern-3-am-control-plane-conf.yaml, advanced/am-pattern-3/templates/am/control-plane/instance-2/wso2am-pattern-3-am-control-plane-deployment.yaml, advanced/am-pattern-3/templates/am/gateway/wso2am-pattern-3-am-gateway-deployment.yaml, advanced/am-pattern-3/templates/mi/instance-1/wso2am-pattern-3-mi-deployment.yaml, advanced/am-pattern-3/values.yaml, advanced/am-pattern-4/requirements.yaml, advanced/am-pattern-4/templates/am/control-plane/instance-1/wso2am-pattern-4-am-control-plane-conf.yaml, advanced/am-pattern-4/templates/am/control-plane/instance-1/wso2am-pattern-4-am-control-plane-deployment.yaml, advanced/am-pattern-4/templates/am/control-plane/instance-2/wso2am-pattern-4-am-control-plane-conf.yaml, advanced/am-pattern-4/templates/am/control-plane/instance-2/wso2am-pattern-4-am-control-plane-deployment.yaml, advanced/am-pattern-4/templates/am/gateway/wso2am-pattern-4-am-gateway-deployment.yaml, advanced/am-pattern-4/templates/am/traffic-manager/instance-1/wso2am-pattern-4-am-trafficmanager-deployment.yaml, advanced/am-pattern-4/templates/am/traffic-manager/instance-2/wso2am-pattern-4-am-trafficmanager-deployment.yaml, advanced/am-pattern-4/templates/mi/wso2am-pattern-4-mi-deployment.yaml, advanced/am-pattern-4/values.yaml
> Parameterize database configuration values  in helm chart
> Deployment.toml conf file contents updated with value.yaml file paramters. 
> Test grid Kubernetes deployment pipeline.
=> Parameterize DB config values in pattern 3 and 4

advanced/am-pattern-1/requirements.yaml, advanced/am-pattern-1/templates/am/instance-1/wso2am-pattern-1-am-conf.yaml, advanced/am-pattern-1/templates/am/instance-1/wso2am-pattern-1-am-deployment.yaml, advanced/am-pattern-1/templates/am/instance-2/wso2am-pattern-1-am-conf.yaml, advanced/am-pattern-1/templates/am/instance-2/wso2am-pattern-1-am-deployment.yaml, advanced/am-pattern-1/templates/mi/instance-1/wso2am-pattern-1-mi-deployment.yaml, advanced/am-pattern-1/values.yaml, advanced/am-pattern-2/templates/mi/instance-2/wso2am-pattern-2-mi-deployment.yaml, advanced/am-pattern-2/values.yaml, simple/am-single/requirements.yaml, simple/am-single/templates/am/instance/wso2am-deployment.yaml, simple/am-single/templates/am/instance/wso2am-single-node-am-conf.yaml, simple/am-single/values.yaml
> Parameterize the database configuration values in helm charts
> Improve the configurability of APIM Helm deployments
=> Parameterize the DB configs

advanced/am-pattern-3/templates/am/control-plane/instance-2/wso2am-pattern-3-am-control-plane-deployment.yaml
=> Fix formatting

advanced/am-pattern-1/templates/am/wso2am-pattern-1-am-service.yaml, advanced/am-pattern-1/templates/am/wso2am-pattern-1-am-websocket-ingress.yaml, advanced/am-pattern-1/values.yaml, advanced/am-pattern-2/values.yaml, advanced/mysql-am/values.yaml, simple/am-single/templates/am/wso2am-websocket-ingress.yaml, simple/am-single/values.yaml
> Add ingress to handle WebSocket traffic
> Update MySQL image to bitnami/mysql to support ARM64
=> Update APIM Helm charts

advanced/am-pattern-3/templates/am/control-plane/instance-1/wso2am-pattern-3-am-control-plane-conf.yaml, advanced/am-pattern-3/templates/am/control-plane/instance-2/wso2am-pattern-3-am-control-plane-conf.yaml, advanced/am-pattern-3/templates/am/control-plane/instance-2/wso2am-pattern-3-am-control-plane-deployment.yaml, advanced/am-pattern-3/templates/am/gateway/wso2am-pattern-3-am-gateway-conf.yaml, advanced/am-pattern-3/templates/am/gateway/wso2am-pattern-3-am-gateway-service.yaml, advanced/am-pattern-3/templates/am/gateway/wso2am-pattern-3-am-websocket-ingress.yaml, advanced/am-pattern-3/values.yaml, advanced/am-pattern-4/templates/am/control-plane/instance-1/wso2am-pattern-4-am-control-plane-conf.yaml, advanced/am-pattern-4/templates/am/control-plane/instance-2/wso2am-pattern-4-am-control-plane-conf.yaml, advanced/am-pattern-4/templates/am/gateway/wso2am-pattern-4-am-gateway-conf.yaml, advanced/am-pattern-4/templates/am/gateway/wso2am-pattern-4-am-gateway-service.yaml, advanced/am-pattern-4/templates/am/gateway/wso2am-pattern-4-am-websocket-ingress.yaml, advanced/am-pattern-4/templates/am/traffic-manager/instance-1/wso2am-pattern-4-am-trafficmanager-conf.yaml, advanced/am-pattern-4/templates/am/traffic-manager/instance-2/wso2am-pattern-4-am-trafficmanager-conf.yaml, advanced/am-pattern-4/values.yaml
> Update deployment.toml configurations in am-pattern-3 and am-pattern-4 according to [1]
> Add an Ingress to handle WebSocket traffic
[1] https://apim.docs.wso2.com/en/latest/install-and-setup/setup/distributed-deployment/deploying-wso2-api-m-in-a-distributed-setup/
=> Update APIM configurations

CHANGELOG.md, README.md, advanced/am-pattern-1/Chart.yaml, advanced/am-pattern-1/README.md, advanced/am-pattern-1/requirements.yaml, advanced/am-pattern-2/Chart.yaml, advanced/am-pattern-2/README.md, advanced/am-pattern-2/requirements.yaml, advanced/am-pattern-3/Chart.yaml, advanced/am-pattern-3/README.md, advanced/am-pattern-3/requirements.yaml, advanced/am-pattern-4/Chart.yaml, advanced/am-pattern-4/README.md, advanced/am-pattern-4/requirements.yaml, advanced/mysql-am/Chart.yaml, simple/am-single/Chart.yaml, simple/am-single/README.md, simple/am-single/requirements.yaml
> Update release version in Helm charts for 4.1.0-2 release
> Update READMEs with websocket ingress configurations
> Update CHANGELOG for 4.1.0-2 release
=> Update Charts and READMEs for 4.1.0-2 release.

advanced/am-pattern-1/templates/am/wso2am-pattern-1-am-service.yaml
=> Fix websocket port name

advanced/am-pattern-1/README.md, advanced/am-pattern-2/README.md, advanced/am-pattern-3/README.md, advanced/am-pattern-4/README.md, simple/am-single/README.md
While deploying Kubernetes artifacts with Rancher Desktop (macOS, Apple M1) several errors were encountered. Refer the issue [[1]](https://github.com/wso2-enterprise/wso2-apim-internal/issues/2299).  This PR updates the documentation with the workarounds to mitigate those issues.
[1] - https://github.com/wso2-enterprise/wso2-apim-internal/issues/2299
=> Add Workarounds for Rancher Desktop to the Documentation

advanced/am-pattern-4/templates/am/control-plane/instance-1/wso2am-pattern-4-am-control-plane-conf.yaml, advanced/am-pattern-4/templates/am/control-plane/instance-1/wso2am-pattern-4-am-control-plane-deployment.yaml, advanced/am-pattern-4/templates/am/control-plane/instance-2/wso2am-pattern-4-am-control-plane-conf.yaml, advanced/am-pattern-4/templates/am/control-plane/instance-2/wso2am-pattern-4-am-control-plane-deployment.yaml, advanced/am-pattern-4/values.yaml
=> Parameterise DB urls in CP

README.md
=> Add disclaimer notice

README.md
=> [4.2.x] Add disclaimer notice

README.md
=> [4.1.x] Add disclaimer notice

README.md
=> [4.0.x] Add disclaimer notice

advanced/am-pattern-2/templates/am-analytics/dashboard/wso2am-pattern-2-am-analytics-dashboard-conf.yaml, advanced/am-pattern-2/templates/am-analytics/dashboard/wso2am-pattern-2-am-analytics-dashboard-deployment.yaml, advanced/am-pattern-2/templates/am-analytics/worker/wso2am-pattern-2-am-analytics-worker-conf.yaml, advanced/am-pattern-2/templates/am-analytics/worker/wso2am-pattern-2-am-analytics-worker-statefulset.yaml, advanced/am-pattern-2/templates/am/gateway/wso2am-pattern-2-am-gateway-deployment.yaml, advanced/am-pattern-2/templates/am/gateway/wso2am-pattern-2-am-gateway-ingress.yaml, advanced/am-pattern-2/templates/am/km/wso2am-pattern-2-am-km-conf.yaml, advanced/am-pattern-2/templates/am/km/wso2am-pattern-2-am-km-statefulset.yaml, advanced/am-pattern-2/templates/am/pub-devportal-tm/instance-1/wso2am-pattern-2-am-conf.yaml, advanced/am-pattern-2/templates/am/pub-devportal-tm/instance-1/wso2am-pattern-2-am-deployment.yaml, advanced/am-pattern-2/templates/am/pub-devportal-tm/instance-2/wso2am-pattern-2-am-conf.yaml, advanced/am-pattern-2/templates/am/pub-devportal-tm/instance-2/wso2am-pattern-2-am-deployment.yaml, advanced/am-pattern-2/values.yaml
Add method to configure database through parameter
=> Add method to configure database through parameter

advanced/am-pattern-1/templates/am/wso2am-pattern-1-am-conf-entrypoint.yaml, advanced/am-pattern-3/templates/am/control-plane/wso2am-pattern-3-am-control-plane-conf-entrypoint.yaml, advanced/am-pattern-4/templates/am/control-plane/wso2am-pattern-4-am-control-plane-conf-entrypoint.yaml, advanced/am-pattern-4/templates/am/traffic-manager/wso2am-pattern-4-am-trafficmanager-conf-entrypoint.yaml, simple/am-single/templates/am/wso2am-conf-entrypoint.yaml
Related issue https://github.com/wso2-enterprise/wso2-apim-internal/issues/4121
=> Remove unused variables from entrypoint

advanced/am-pattern-1/templates/am/wso2am-pattern-1-am-conf-entrypoint.yaml, advanced/am-pattern-3/templates/am/control-plane/wso2am-pattern-3-am-control-plane-conf-entrypoint.yaml, advanced/am-pattern-4/templates/am/control-plane/wso2am-pattern-4-am-control-plane-conf-entrypoint.yaml, advanced/am-pattern-4/templates/am/traffic-manager/wso2am-pattern-4-am-trafficmanager-conf-entrypoint.yaml, simple/am-single/templates/am/wso2am-conf-entrypoint.yaml
Related issue https://github.com/wso2-enterprise/wso2-apim-internal/issues/4121
=> [4.2.x] Remove unused variables from entrypoint

advanced/am-pattern-1/README.md, advanced/am-pattern-2/README.md, advanced/am-pattern-3/README.md, advanced/am-pattern-4/README.md
Removing wso2.deployment.mi.config as that is not used, MI config mapper templating will be done by https://github.com/wso2/micro-integrator/issues/2950
> Brief description of the new feature or bug fix as it will …
=> Remove wso2.deployment.mi.config from readme files

advanced/am-pattern-1/README.md, advanced/am-pattern-1/templates/mi/instance-1/wso2am-pattern-1-mi-conf.yaml, advanced/am-pattern-1/templates/mi/instance-1/wso2am-pattern-1-mi-deployment.yaml, advanced/am-pattern-1/values.yaml, advanced/am-pattern-2/README.md, advanced/am-pattern-2/templates/mi/instance-2/wso2am-pattern-2-mi-conf.yaml, advanced/am-pattern-2/templates/mi/instance-2/wso2am-pattern-2-mi-deployment.yaml, advanced/am-pattern-2/values.yaml, advanced/am-pattern-3/README.md, advanced/am-pattern-3/templates/mi/instance-1/wso2am-pattern-3-mi-conf.yaml, advanced/am-pattern-3/templates/mi/instance-1/wso2am-pattern-3-mi-deployment.yaml, advanced/am-pattern-3/values.yaml, advanced/am-pattern-4/README.md, advanced/am-pattern-4/templates/mi/wso2am-pattern-4-mi-conf.yaml, advanced/am-pattern-4/templates/mi/wso2am-pattern-4-mi-deployment.yaml, advanced/am-pattern-4/values.yaml
Add option to define the toml configs via Helm
Fixes: https://github.com/wso2/micro-integrator/issues/2950
=> Add option to define the toml configs via Helm

advanced/am-pattern-1/README.md, advanced/am-pattern-1/templates/mi/instance-1/wso2am-pattern-1-mi-conf.yaml, advanced/am-pattern-1/templates/mi/instance-1/wso2am-pattern-1-mi-deployment.yaml, advanced/am-pattern-1/values.yaml, advanced/am-pattern-2/README.md, advanced/am-pattern-2/templates/mi/instance-2/wso2am-pattern-2-mi-conf.yaml, advanced/am-pattern-2/templates/mi/instance-2/wso2am-pattern-2-mi-deployment.yaml, advanced/am-pattern-2/values.yaml, advanced/am-pattern-3/README.md, advanced/am-pattern-3/templates/mi/instance-1/wso2am-pattern-3-mi-conf.yaml, advanced/am-pattern-3/templates/mi/instance-1/wso2am-pattern-3-mi-deployment.yaml, advanced/am-pattern-3/values.yaml, advanced/am-pattern-4/README.md, advanced/am-pattern-4/templates/mi/wso2am-pattern-4-mi-conf.yaml, advanced/am-pattern-4/templates/mi/wso2am-pattern-4-mi-deployment.yaml, advanced/am-pattern-4/values.yaml
Add option to define the toml configs via Helm
Fixes: https://github.com/wso2/micro-integrator/issues/2950
=> [420] Add option to define the toml configs via Helm

advanced/am-pattern-1/Chart.yaml, advanced/am-pattern-2/Chart.yaml, advanced/am-pattern-3/Chart.yaml, advanced/am-pattern-4/Chart.yaml
=> Bump chart version

simple/am-single/Chart.yaml
=> Bump chart version for single node

README.md
=> Add note about repository deprecation and redirect to new Helm charts
